# frozen_string_literal: true

IMAGE_NAME = 'ubuntu/bionic64'
N = 2
PROJECT = 'k3s'
NETWORK_PREFIX = ENV['NETWORK_PREFIX'] || '192.168.50'
NETWORK_ID = 2

# --- Check for missing plugins
required_plugins = %w[vagrant-alpine vagrant-timezone]
plugin_installed = false
required_plugins.each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    system "vagrant plugin install #{plugin}"
    plugin_installed = true
  end
end
# --- If new plugins installed, restart Vagrant process
exec "vagrant #{ARGV.join ' '}" if plugin_installed === true

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false

  config.vm.provider 'virtualbox' do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ['modifyvm', :id, '--audio', 'none']
  end

  # install docker
  config.vm.provision 'shell', inline: <<-SHELL
      apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common

      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"

      apt-get update

      apt-get install -y docker-ce docker-ce-cli containerd.io

      usermod -aG docker vagrant
  SHELL

  # install tools
  config.vm.provision 'shell', inline: <<-SHELL
      apt-get install -y git vim
  SHELL

  config.vm.synced_folder '/Users/wusendong', '/hosthome'
  config.timezone.value = :host

  config.vm.define "#{PROJECT}-master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network 'private_network', ip: "#{NETWORK_PREFIX}.#{NETWORK_ID}0"
    master.vm.hostname = "#{PROJECT}-#{NETWORK_ID}0"

    # master.vm.provision "ansible" do |ansible|
    #     ansible.playbook = "kubernetes-setup/master-playbook.yml"
    #     ansible.extra_vars = {
    #         node_ip: "192.168.50.10",
    #     }
    # end
    config.vm.provision 'shell', inline: <<-SHELL
          curl -sfL https://get.k3s.io | sh -
          cp /var/lib/rancher/k3s/server/node-token /vagrant/
    SHELL
  end

  (1..N).each do |i|
    config.vm.define "#{PROJECT}-#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network 'private_network', ip: "#{NETWORK_PREFIX}.#{NETWORK_ID}#{i}"
      node.vm.hostname = "#{PROJECT}-#{NETWORK_ID}#{i}"

      # node.vm.provision "ansible" do |ansible|
      #     ansible.playbook = "kubernetes-setup/node-playbook.yml"
      #     ansible.extra_vars = {
      #         node_ip: "192.168.50.#{i + 10}",
      #     }
      # end
      config.vm.provision 'shell', inline: <<-SHELL
              export K3S_TOKEN=`cat /vagrant/node-token`
              export K3S_URL="https://192.168.50.20:6444"
              curl -sfL https://get.k3s.io | sh -
      SHELL
    end
  end
end
