# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  config.vm.provision "shell", path:"install_docker.sh"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y git
  SHELL

  config.vm.define "k8s21" do |k8s21|
    k8s21.vm.hostname = 'k8s21'
    k8s21.vm.box= "ubuntu/xenial64"
    k8s21.vm.box_url = "ubuntu/xenial64"
    config.ssh.username = 'ubuntu'

    k8s21.vm.network :private_network, ip: "172.22.101.21",
      nic_type: "82545EM"

    k8s21.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "k8s21"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end

  config.vm.define "k8s22" do |k8s22|
    k8s22.vm.hostname = 'k8s22'
    k8s22.vm.box= "ubuntu/xenial64"
    k8s22.vm.box_url = "ubuntu/xenial64"
    config.ssh.username = 'ubuntu'

    k8s22.vm.network :private_network, ip: "172.22.101.22",
      nic_type: "82545EM"

    k8s22.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "k8s22"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end


end
