# frozen_string_literal: true

IMAGE_NAME = 'ubuntu/bionic64'
N = 1
PROJECT = 'k8s'
HOSTHOME = ENV['HOME'] || '.'
NETWORK_PREFIX = ENV['NETWORK_PREFIX'] || '192.168.90'
NETWORK_ID = 2

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false
  config.vagrant.plugins = ['vagrant-timezone']
  config.timezone.value = :host
  config.vm.synced_folder HOSTHOME, '/hosthome'
  config.vm.synced_folder '/', '/host'
  config.vm.provider 'virtualbox' do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ['modifyvm', :id, '--audio', 'none']
    v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
  end

  config.vm.define 'k8s-master' do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network 'private_network', ip: "#{NETWORK_PREFIX}.#{NETWORK_ID}0"
    master.vm.hostname = 'k8s-master'
    master.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'kubernetes-setup/master-playbook.yml'
      ansible.extra_vars = {
        node_ip: "#{NETWORK_PREFIX}.#{NETWORK_ID}0"
      }
    end
  end

  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network 'private_network', ip: "#{NETWORK_PREFIX}.#{NETWORK_ID}#{i}"
      node.vm.hostname = "node-#{i}"
      node.vm.provision 'ansible' do |ansible|
        ansible.playbook = 'kubernetes-setup/node-playbook.yml'
        ansible.extra_vars = {
          node_ip: "#{NETWORK_PREFIX}.#{NETWORK_ID}#{i}"
        }
      end
    end
  end
end
